### ISSUE TITLE
Deadlock 


### ISSUE THREAD

**Issue by StefanoPrivitera** [BowTiedDevil/degenbot#15]
I tried to calculate the output amount, given an input amount for a specific pool via the function lp.calculate_tokens_out_from_tokens_in
the software remains deadlocked, how can I solve this?

`import web3
import degenbot

w3 = web3.Web3(web3.HTTPProvider("https://mainnet.infura.io/v3/xxxxx"))
degenbot.set_web3(w3)
lp=degenbot.V3LiquidityPool('0x3416cf6c708da44db2624d63ea0aaef7113527c6')
   
o=lp.calculate_tokens_out_from_tokens_in(token_in=lp.token1, token_in_quantity=1*10**18)
print(o)`

Thank you very much

**Comment by BowTiedDevil** [comment]
Thank you for the report! It helped me identify an infinite loop, which I've fixed by the referenced commit.
