### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by royyannick** [BowTiedDevil/degenbot#6]
No requirements.txt to install the relevant packages?

**Comment by cnukaus** [comment]
eth-brownie
scipy
eth_abi==2.2.0
bip32utils
websockets==???b

**Comment by BowTiedDevil** [comment]
I've pushed the relevant dependencies to `pyproject.toml` in commit 6b2656d2607c597e34e1f2a069e7fad3748ded99, so installation with `pip` will fetch all required packages.
